#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768
#define BLOCK_WIDTH 340
#define BLOCK_HEIGHT 50
#define WINDOW_PADDING 50
#define TEXTFIELD_TOP WINDOW_HEIGHT/3
#define TEXTFIELD_OFS (3*WINDOW_HEIGHT/4 - 2*WINDOW_PADDING)

#define KEYBIND_SHOW_WIDTH WINDOW_WIDTH/2
#define NORMDELTA 0.5

// textFieldのpadding
#define TEXTFIELD_PADDING WINDOW_PADDING+25
